Update main.py
Line 25: cam = PICamera()
When this is used on the Astro Pi it comes up with this error:

File "/usr/lib/python3/dist-packages/picamera/mmalobj.py", line 348, in open_stream
    stream.write
AttributeError: 'PosixPath' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/mu_code/main.py", line 108, in <module>
    capture(cam, image_file)
  File "/home/pi/mu_code/main.py", line 73, in capture
    camera.capture(image)
  File "/usr/lib/python3/dist-packages/picamera/camera.py", line 1418, in capture
    encoder.start(output)
  File "/usr/lib/python3/dist-packages/picamera/encoders.py", line 1126, in start
    super(PiCookedOneImageEncoder, self).start(output)
  File "/usr/lib/python3/dist-packages/picamera/encoders.py", line 375, in start
    self._open_output(output)
  File "/usr/lib/python3/dist-packages/picamera/encoders.py", line 331, in _open_output
    self.outputs[key] = mo.open_stream(output)
  File "/usr/lib/python3/dist-packages/picamera/mmalobj.py", line 354, in open_stream
    stream = BufferIO(stream)
  File "/usr/lib/python3/dist-packages/picamera/streams.py", line 64, in __init__
    self._buf = memoryview(obj)
TypeError: memoryview: a bytes-like object is required, not 'PosixPath'

But with it as 'cam = PiCamera', this error comes up:

File "/home/pi/mu_code/main.py", line 109, in <module>
    capture(cam, image_file)
  File "/home/pi/mu_code/main.py", line 69, in capture
    camera.exif_tags['GPS.GPSLatitude'] = exif_latitude
TypeError: 'property' object does not support item assignment